# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 华仔-Chandler
email: huanghuang240@163.com
description: > # this means to ignore newlines until "baseurl:"
  演绎,在前端
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: chandler
github_username:  pisse
facebook_username: chandler

# Build settings
markdown: kramdown


comments: true

# Site owner
owner:
  disqus-shortname: monicaye
